# Generated by Django 6.0.3 on 2026-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_project_rename_skills_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text="Enter FontAwesome class (e.g., 'fab fa-python', 'fas fa-database')", max_length=100),
        ),
    ]
