# Generated by Django 6.0.3 on 2026-04-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='', upload_to='project_images/'),
            preserve_default=False,
        ),
    ]
